### ISSUE TITLE
1.1 APK shows up as 1.0

### ISSUE THREAD

**Issue by IzzySoft** [robinpaulson/SimpleRT#33] opened 2017-05-21 22:00 UTC
The `.apk` attached to the 1.1 tag, if installed, shows up as version 1.0. Looking at the package itself, it seems `versionCode` and `versionName` are set incorrectly:

    package: name='com.viper.simplert' versionCode='1' versionName='1.0' platformBuildVersionName='N'

As there already was a v1.0 before that, `versionCode` must have been increased – and `versionName` should reflect the real version number :smile_cat: 

So may I suggest to correct that? And when attaching the fixed `.apk`, please leave it an `.apk` and do not ZIP it again. Thanks in advance!

**Comment by IzzySoft** [comment] 2017-06-23 22:47
Any chance?

**Comment by vvviperrr** [comment] 2017-06-28 13:15
hi. i leave 1.0 version in binary to support backward compatibility, so u can use simple-rt cli v1.1 with 1.1 AND 1.0 apk version. so, its not an issue.
thanks.

**Comment by IzzySoft** [comment] 2017-06-28 13:58
Ah, I see. Just wonder that it's named `simple-rt-1.1.apk.zip` and its size differes from the one attached to the 1.0 tag. Plus, the comment in the release note says "works only with 1.1 (this) apk version" – which seems to contradict what you just wrote. Maybe you adjust the release comments then, to avoid that confusion? :wink:

**Comment by robinpaulson** [comment] 2021-11-24 02:32
@IzzySoft I made a new release, it will likely hit the FD repos in a few days, could you take a look to see if the problem is fixed? I'm still looking around the code, the first month or so since I took over got interrupted by ... life.

**Comment by IzzySoft** [comment] 2021-11-24 07:57
When a new version shows up, you can consider the issue solved. When I reported this issue here 4 years ago, the app was in my repo (so I noticed); it no longer is, it's now at F-Droid.org. And someone already updated the metadata yesterday (as this issue was left unanswered for years, updates had been disabled), so it indeed could show up within the next few days. A new build cycle has just started, you can [watch it here](https://monitor.f-droid.org/builds/running).

**Comment by robinpaulson** [comment] 2021-12-04 11:04
This should be fixed now, I released v1.1.1

Closing, do post if there are any issues related to this

**Closed** 2021-12-04 11:04 UTC
Labels: packaging

**Comment by IzzySoft** [comment] 2021-12-04 13:10
Confirmed: v1.1.1 showed up on F-Droid 2 days ago. Thanks!
